# ------------------------------------------------------------------------------
# 📄 Config File: run_final_audit_config.yaml
# 🧩 Module: Final Audit & Certification (M10)
# 📌 Purpose: Applies final edits, runs a certification pass, and produces
#            a capstone report summarizing the pipeline's data transformations.
# ------------------------------------------------------------------------------
# This module is the last quality gate before dataset delivery.
# It compares raw vs cleaned data, drops artifacts, certifies schema, 
# and generates final reports and lifecycle stats.
# ------------------------------------------------------------------------------

# 📥 Execution context
run_id: ""
notebook: true
logging: "auto"                # Options: 'on', 'off', or 'auto'

# 🧮 Final audit configuration
final_audit:
  run: true

  # 📂 Input paths
  input_df_path: "exports/joblib/{run_id}/{run_id}_m07_df_imputed.joblib"
  raw_data_path: "data/raw/synthetic_penguins_v3.5.csv"

  # 🧼 Final edits before certification
  final_edits:
    run: true
    drop_columns:
      - 'example'
    rename_columns: {}
    coerce_dtypes: {}

  # ✅ Certification block (invokes validation logic in strict mode)
  certification:
    run: true
    fail_on_error: true

    rules:
      expected_columns: 
        - "example"

      expected_types:
        example: "object"
        
      categorical_values:
       example: ["UNKNOWN"]

      # 🚫 Columns that must not contain nulls
      disallowed_null_columns:
        - 'example'

  # 📤 Reporting and checkpoint settings
  settings:
    show_inline: true
    export_report: true

    paths:
      report_excel: "exports/reports/final_audit/{run_id}_FinalAuditReport.xlsx"
      report_joblib: "exports/reports/final_audit/{run_id}_FinalAuditReport.joblib"
      checkpoint_csv: "data/processed/{run_id}_penguins_certified.csv"
      checkpoint_joblib: "exports/joblib/{run_id}/{run_id}_penguins_certified.joblib"
      plot_save_dir: "exports/plots/final_audit/{run_id}/"