name: analyst-toolkit
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel=6.25.2
  - jupyter=1.0.0
  - pandas=2.1.0
  - numpy=1.25.2
  - seaborn=0.13.0
  - matplotlib=3.7.3
  - openpyxl=3.1.2
  - joblib=1.3.2
  - pyyaml=6.0.1
  - black
  - flake8
  - pip:
      - git+https://github.com/G-Schumacher44/analyst_toolkit.git@main
