name: Build Deployment Zip

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      note:
        description: Optional note for this build
        required: false

# Grant GITHUB_TOKEN the ability to create releases and upload assets
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build deploy bundle
        run: |
          if [ -f deploy_toolkit/scripts/package_bundle.py ]; then
            python deploy_toolkit/scripts/package_bundle.py
          else
            echo "Packager script missing in this ref; using git archive fallback"
            git archive -o deploy_bundle.zip --format=zip HEAD
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy_bundle
          path: deploy_bundle.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy_bundle
          path: .

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            deploy_bundle.zip#deploy_toolkit.zip
          generate_release_notes: true
