name: <my—env>
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - jupyter
  - pandas
  - numpy>=1.26.0
  - scipy
  - seaborn
  - matplotlib>=3.7.3
  - openpyxl
  - joblib
  - pyyaml
  - black
  - flake8
  - pip:
      - git+https://github.com/G-Schumacher44/analyst_toolkit.git@v0.2.0
      - git+https://github.com/G-Schumacher44/analyst_toolkit_deployment_utility.git@v0.2.5
